site_name: My Docs

nav:
  - index : index.md
  - learn : 
    - CPP :
      - C++ primer :
        - chapter 2 : D:\myblog\docs\Learn_docs\CPP\C++ primer\chapter2\README.md
      - CPP_oneflow_school : D:\myblog\docs\Learn_docs\CPP\CPP_oneflow_shcool\01-mem-and-pointer.md
      - CPP_oneflow_school : D:\myblog\docs\Learn_docs\CPP\CPP_oneflow_shcool\02-pointerII-fun-stack.md

